# Site settings
title: Fabryka Równości # site title
timezone: Europe/Warsaw # set your timezone
mode: light # default theme "dark" | "light"

  
# URL settings
url: " " 
baseurl: ""
permalink: /:title/

# Build settings
#theme: rownasie
sass:
  style: :compresed
  sass_dir: _sass

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-include

include:
  - _content